#+TITLE: Tarea 1

- Mezcla los comandos =httppie=, =jq= y =csvkit= para descargar las películas de *Star Wars* y guardar los campos de
  =title,episode_id,director,producer,release_date,opening_crawl= en una base de
  datos =sqlite= llamada =star_wars.db=.

http http://swapi.co/api/films/ | jq '.results[] | {"title":.title,
                                "episode_id":.episode_id,
                                "director": .director,"producer":.producer,
                                "release_date": .release_date, "opening_crawl":.opening_crawl} ' | join("\n ") |in2csv -f ndjson  > try1.csv


http http://swapi.co/api/films/ |jq -r '.results |[(map(keys) | add | unique)[11,4,2,7,8,5]] as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' > films.csv

http http://swapi.co/api/films/ |jq  -r '.results |[(map(keys) | add | unique)[11,4,2,7,8,5]] as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' | csvsql -i postgresql  | csvsql --db sqlite:///star_wars.db --insert
sql2csv --db sqlite:///star_wars.db --query "select * from star_wars"


- Usando =bash= crea un programa que descargue todas los /resources/ de *SWAPI*

  #+BEGIN_EXAMPLE shell
  http GET http://swapi.co/api/
  #+END_EXAMPLE

  y guárdalos en =jsons= separados usando como nombres de archivo la llave del
  =json=.

  Toma en cuenta la paginación. Al final deberás de tener sólo 7 archivos.

  Procesa estos archivos con las herramientas del primer inciso de la tarea. Al
  final deberías de tener 7 tablas en =star_wars.db=

- Repite el inciso anterior, pero ahora usando =aws= y =parallel=. Crea 7 instancias de =Amazon EC2=,
  y en cada una procesa como antes. Distribuye los archivos de ejecución y luego tráelos a tu máquina local para
  guardarlos en una base de datos =sqlite=.

  *NOTA* ¡No olvides apagar las máquinas!




http GET http://swapi.co/api/

http http://swapi.co/api/ | jq '.people' |  tr -d '"'